// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// CicdPipeline is the golang structure for table cicd_pipeline.
type CicdPipeline struct {
	Id           uint   `orm:"id,primary"           json:"id"`           //
	PipelineName string `orm:"pipeline_name,unique" json:"pipelineName"` //
	GroupId      int    `orm:"group_id"             json:"groupId"`      //
	AgentId      int    `orm:"agent_id"             json:"agentId"`      //
	Body         string `orm:"body"                 json:"body"`         //
	Author       string `orm:"author"               json:"author"`       //
	UpdatedAt    int64  `orm:"updated_at"           json:"updatedAt"`    //
}

// CicdJob is the golang structure for table cicd_job.
type CicdJob struct {
	Id         int64  `orm:"id,primary"  json:"id"`         //
	PipelineId int    `orm:"pipeline_id" json:"pipelineId"` //
	AgentId    int    `orm:"agent_id"    json:"agentId"`    //
	JobType    string `orm:"job_type"    json:"jobType"`    //
	JobStatus  string `orm:"job_status"  json:"jobStatus"`  //
	Script     string `orm:"script"      json:"script"`     //
	Comment    string `orm:"comment"     json:"comment"`    //
	Author     string `orm:"author"      json:"author"`     //
	CreatedAt  int64  `orm:"created_at"  json:"createdAt"`  //
}

// CicdScript is the golang structure for table cicd_script.
type CicdScript struct {
	Id         int    `orm:"id,primary"         json:"id"`         //
	ScriptName string `orm:"script_name,unique" json:"scriptName"` //
	ScriptBody string `orm:"script_body"        json:"scriptBody"` //
	Author     string `orm:"author"             json:"author"`     //
	UpdatedAt  int64  `orm:"updated_at"         json:"updatedAt"`  //
}

// CicdAgent is the golang structure for table cicd_agent.
type CicdAgent struct {
	Id        int    `orm:"id,primary"        json:"id"`        //
	AgentName string `orm:"agent_name,unique" json:"agentName"` //
	UpdatedAt int64  `orm:"updated_at"        json:"updatedAt"` //
}

// CicdLog is the golang structure for table cicd_log.
type CicdLog struct {
	Id        int64  `orm:"id,primary" json:"id"`        //
	JobId     int    `orm:"job_id"     json:"jobId"`     //
	JobStatus string `orm:"job_status" json:"jobStatus"` //
	Ipaddr    string `orm:"ipaddr"     json:"ipaddr"`    //
	UpdatedAt int64  `orm:"updated_at" json:"updatedAt"` //
	Output    string `orm:"output"     json:"output"`    //
}

// CicdPackage is the golang structure for table cicd_package.
type CicdPackage struct {
	Id          int64  `orm:"id,primary"    json:"id"`          //
	PipelineId  int    `orm:"pipeline_id"   json:"pipelineId"`  //
	JobId       int    `orm:"job_id,unique" json:"jobId"`       //
	JobStatus   string `orm:"job_status"    json:"jobStatus"`   //
	PackageName string `orm:"package_name"  json:"packageName"` //
	CreatedAt   int64  `orm:"created_at"    json:"createdAt"`   //
}

// CicdGroup is the golang structure for table cicd_group.
type CicdGroup struct {
	Id        int    `orm:"id,primary" json:"id"`        //
	GroupName string `orm:"group_name" json:"groupName"` //
	ParentId  int    `orm:"parent_id"  json:"parentId"`  //
}

// CicdUser is the golang structure for table cicd_user.
type CicdUser struct {
	Id        uint   `orm:"id,primary"   json:"id"`        //
	Email     string `orm:"email,unique" json:"email"`     //
	Password  string `orm:"password"     json:"password"`  //
	GroupId   string `orm:"group_id"     json:"groupId"`   //
	UpdatedAt int64  `orm:"updated_at"   json:"updatedAt"` //
}
