// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdAgentDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdAgentDao struct {
	*internal.CicdAgentDao
}

var (
	// CicdAgent is globally public accessible object for table cicd_agent operations.
	CicdAgent cicdAgentDao
)

func init() {
	CicdAgent = cicdAgentDao{
		internal.NewCicdAgentDao(),
	}
}

// Fill with you ideas below.
