// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdUserDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdUserDao struct {
	*internal.CicdUserDao
}

var (
	// CicdUser is globally public accessible object for table cicd_user operations.
	CicdUser cicdUserDao
)

func init() {
	CicdUser = cicdUserDao{
		internal.NewCicdUserDao(),
	}
}

// Fill with you ideas below.
