// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdGroupDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdGroupDao struct {
	*internal.CicdGroupDao
}

var (
	// CicdGroup is globally public accessible object for table cicd_group operations.
	CicdGroup cicdGroupDao
)

func init() {
	CicdGroup = cicdGroupDao{
		internal.NewCicdGroupDao(),
	}
}

// Fill with you ideas below.
