// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdLogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdLogDao struct {
	*internal.CicdLogDao
}

var (
	// CicdLog is globally public accessible object for table cicd_log operations.
	CicdLog cicdLogDao
)

func init() {
	CicdLog = cicdLogDao{
		internal.NewCicdLogDao(),
	}
}

// Fill with you ideas below.
