// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdPackageDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdPackageDao struct {
	*internal.CicdPackageDao
}

var (
	// CicdPackage is globally public accessible object for table cicd_package operations.
	CicdPackage cicdPackageDao
)

func init() {
	CicdPackage = cicdPackageDao{
		internal.NewCicdPackageDao(),
	}
}

// Fill with you ideas below.
