// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tangr/cicdgo/app/dao/internal"
)

// cicdJobDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type cicdJobDao struct {
	*internal.CicdJobDao
}

var (
	// CicdJob is globally public accessible object for table cicd_job operations.
	CicdJob cicdJobDao
)

func init() {
	CicdJob = cicdJobDao{
		internal.NewCicdJobDao(),
	}
}

// Fill with you ideas below.
