// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CicdAgentDao is the manager for logic model data accessing and custom defined data operations functions management.
type CicdAgentDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      cicdAgentColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// CicdAgentColumns defines and stores column names for table cicd_agent.
type cicdAgentColumns struct {
	Id        string //
	AgentName string //
	Ipaddr    string //
	UpdatedAt string //
}

// NewCicdAgentDao creates and returns a new DAO object for table data access.
func NewCicdAgentDao() *CicdAgentDao {
	columns := cicdAgentColumns{
		Id:        "id",
		AgentName: "agent_name",
		Ipaddr:    "ipaddr",
		UpdatedAt: "updated_at",
	}
	return &CicdAgentDao{
		C:     columns,
		M:     g.DB("default").Model("cicd_agent").Safe(),
		DB:    g.DB("default"),
		Table: "cicd_agent",
	}
}
