// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CicdGroupDao is the manager for logic model data accessing and custom defined data operations functions management.
type CicdGroupDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      cicdGroupColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// CicdGroupColumns defines and stores column names for table cicd_group.
type cicdGroupColumns struct {
	Id        string //
	GroupName string //
	ParentId  string //
}

// NewCicdGroupDao creates and returns a new DAO object for table data access.
func NewCicdGroupDao() *CicdGroupDao {
	columns := cicdGroupColumns{
		Id:        "id",
		GroupName: "group_name",
		ParentId:  "parent_id",
	}
	return &CicdGroupDao{
		C:     columns,
		M:     g.DB("default").Model("cicd_group").Safe(),
		DB:    g.DB("default"),
		Table: "cicd_group",
	}
}
