// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CicdScriptDao is the manager for logic model data accessing and custom defined data operations functions management.
type CicdScriptDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      cicdScriptColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB            // DB is the raw underlying database management object.
	Table  string            // Table is the underlying table name of the DAO.
}

// CicdScriptColumns defines and stores column names for table cicd_script.
type cicdScriptColumns struct {
	Id         string //
	ScriptName string //
	ScriptBody string //
	Author     string //
	UpdatedAt  string //
}

// NewCicdScriptDao creates and returns a new DAO object for table data access.
func NewCicdScriptDao() *CicdScriptDao {
	columns := cicdScriptColumns{
		Id:         "id",
		ScriptName: "script_name",
		ScriptBody: "script_body",
		Author:     "author",
		UpdatedAt:  "updated_at",
	}
	return &CicdScriptDao{
		C:     columns,
		M:     g.DB("default").Model("cicd_script").Safe(),
		DB:    g.DB("default"),
		Table: "cicd_script",
	}
}
